### ISSUE TITLE
typeError

### ISSUE THREAD

**Issue by shindekokoro** [codyc1515/homebridge-ismartgate#11]
```
TypeError: Cannot read properties of undefined (reading 'length')
    at checkFormat (/usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/service_type.js:240:11)
    at exports.ServiceType.fromString (/usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/service_type.js:118:5)
    at new exports.ServiceType (/usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/service_type.js:31:14)
    at /usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/decoder.js:40:27
    at /usr/lib/node_modules/homebridge-ismartgate/node_modules/dns-js/lib/dnspacket.js:223:7
    at Array.forEach (<anonymous>)
    at module.exports.each (/usr/lib/node_modules/homebridge-ismartgate/node_modules/dns-js/lib/dnspacket.js:221:17)
    at module.exports.decodeSection (/usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/decoder.js:26:10)
    at /usr/lib/node_modules/homebridge-ismartgate/node_modules/mdns-js/lib/decoder.js:111:5
    at Array.forEach (<anonymous>)
```

Getting this error, causing a SIGTERM on hombridge service. Not exactly what the error is, didn't see much in the logs. I have added a check to the node module mdns-js "service_type.js" on line 240, **if (str === undefined || str.length === 0) {** Will update if that solves the problem. This does not appear to be an actual problem with this plugin more as an issue with the module.

**Comment by shindekokoro** [comment]
Alright, so looks like the error is still causing a SIGTEM to hombridge. Now It just errors out a little more gracefully, I'll do some more research someone has an idea on what would be causing the error.

**Comment by shindekokoro** [comment]
After some more research with the same error having occurred for awhile now. I was looking closer at the code for possible reasons and saw on the mdns-js code example/readme:

```
 //if you have another mdns daemon running, like avahi or bonjour, uncomment following line
//mdns.excludeInterface('0.0.0.0');
```

I added that line of code to this plugin and it appears to have resolved that error. I still receive a TypeError, just a different one now. 

```
TypeError: Cannot read properties of null (reading 'headers')
    at iSmartGate._refresh (/usr/lib/node_modules/homebridge-ismartgate/index.js:124:35)
    at iSmartGate.<anonymous> (/usr/lib/node_modules/homebridge-ismartgate/index.js:79:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

I'll continue to look into this problem to see if I can get a complete resolution.

**Comment by codyc1515** [comment]
Looks like there is more than one mDNS service running. In any case, I would suggest to check out Home Assistant which has a native iSmartGate integration available.
