### ISSUE TITLE
captcha required on latest firmware

### ISSUE THREAD

**Issue by schemers** [codyc1515/homebridge-ismartgate#4]
Thought I'd try out your plugin, and it was having trouble logging in.

I recently installed mine, and the firmware version is `1.6.3`. 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/249172/87254140-42212280-c435-11ea-96aa-6cf8b9c7de5f.png">

**Comment by schemers** [comment]
I'm wondering if the solution might require configuring cookie(s) to use instead of username/password.

i.e., login into the browser (with "Remember Access" checked), grab the cookie(s), and add to config.

The only question is how long that cookie would be good far. Given the warning you get when "Remember Access" is checked it might be good for a while.

**Comment by schemers** [comment]
hum, interesting. Subsequent logins (after clicking remember access and logging out)  didn't have the captcha. I also noticed that three cookies are set, one a `PHPSESSID` cookie that expires when browsing session ends, and two others that expire in two years, so it might be possible to use those two cookies. If I get a second I'll try it out.

**Comment by schemers** [comment]
still got the same error from curl your plugin was logging: `Restricted Access%`. 

After deleting my cookies and hitting the web page again, I see no captcha, so it could be repeated request failures from the plugin (there were quite a few) put it into 'captcha` mode for a brief time. 

The release notes for 1.6.3 are:

### RELEASE NOTES
**Version 1.6.3**
- Added Samsung SmartThings compatibility
- Security vulnerabilities fixed
- Minor bug fixes and enhancements

So maybe they changed things and the API you are trying to use is no longer valid.

**Comment by codyc1515** [comment]
Are you still experiencing this issue?

**Comment by schemers** [comment]
Hey. I tried a little more (back in July) and wasn't able to get it to work. Haven't revisited. It is a smart gate pro, so not sure if that had anything to do with it. Feel free to close this if no one else has reported issues.

**Comment by rnilssoncx** [comment]
I am also having it say "Restricted Access" as well as "Login Token Expired"

**Comment by samwelnella** [comment]
I'm having the same issues with "Restricted Access" and "Login Token Expired"

**Comment by discofris** [comment]
```
[1/16/2022, 10:02:12 AM] [iSmartGate Temperature] Found an iSmartGate at 192.168.1.9

[1/16/2022, 10:02:15 AM] [iSmartGate Temperature] Logged into iSmartGate succesfully

[1/16/2022, 10:02:15 AM] [iSmartGate Temperature] Login token expired.

[1/16/2022, 10:02:15 AM] TypeError: this.log.warning is not a function
    at iSmartGate.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/index.js:148:34)
    at Request.self.callback (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

[1/16/2022, 10:02:15 AM] Got SIGTERM, shutting down Homebridge...
```

And no setting on the device allow us to disable the Captcha 👎

**Comment by codyc1515** [comment]
Can you update your install & please try again? It looks like an exception was not handled correctly. Also are you experiencing the captcha on the device? You shouldn't get this if the password is correct. Can you try restarting the iSmartgate if you got the captcha?

**Comment by discofris** [comment]
My homebridge is on version 1.3.9, your plugin is now 1.4.2 and my iSmartgate is 1.6.6. The captcha is/was on the login page. After a restart of my device is not anymore on the login page?!

Anyway, log shows now:

```
[1/16/2022, 11:49:17 AM] [iSmartGate Temperature] Launched child bridge with PID 16830
[1/16/2022, 11:49:17 AM] Registering accessory 'homebridge-ismartgate.iSmartGate'
[1/16/2022, 11:49:18 AM] [iSmartGate Temperature] Loaded homebridge-ismartgate v1.4.2 child bridge successfully
[1/16/2022, 11:49:18 AM] Loaded 0 cached accessories from cachedAccessories.0E61xxxxxxxx.
[1/16/2022, 11:49:18 AM] Homebridge v1.3.9 (HAP v0.9.8) (iSmartGate Temperature) is running on port 53813.
[1/16/2022, 11:49:18 AM] [iSmartGate Temperature] Found an iSmartGate at 192.168.1.9
[1/16/2022, 11:49:21 AM] [iSmartGate Temperature] Logged into iSmartGate succesfully
[1/16/2022, 11:49:21 AM] [iSmartGate Temperature] Restricted Access Restricted Access
[1/16/2022, 11:49:21 AM] [iSmartGate Temperature] Unexpected BatteryLevel detected. Restricted Access
[1/16/2022, 11:49:21 AM] [homebridge-ismartgate] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
```

Plugin is alreada a child-bridge.
Temp and batt are shown on the admin pages:
![image](https://user-images.githubusercontent.com/6281711/149657006-abedea9e-03f9-4c1d-a04c-82de09a21fb2.png)


Now with debug mode on:

```
[1/16/2022, 11:59:34 AM] [homebridge-ismartgate] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at CurrentTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1415:20)
    at iSmartGate.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/index.js:155:93)
    at Request.self.callback (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-ismartgate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
```

**Comment by discofris** [comment]
Hh boy ... despite the plugin config says "Default: admin" and nothing is filled into the field Username ... the json.config does not have a field username

Filled in admin as Username and all is working great now :-)

![image](https://user-images.githubusercontent.com/6281711/149770651-bb03d7e4-4031-49b5-8880-0a18e87b1abe.png)

Sorry ...

**Comment by codyc1515** [comment]
Good catch! You may wish to check out Home Assistant which has a native iSmartGate integration.
